name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gleam_packages_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: erlef/setup-beam@v1.15.0
        with:
          otp-version: "24.2"
          gleam-version: "0.28.2"
          rebar3-version: "3"
      - run: gleam format --check src test
      - run: gleam test
